# Generated by Django 6.0.7 on 2026-07-16 09:58

import apps.accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Otasining ismi"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon raqami +998901234567 formatida bo'lishi kerak.",
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Mutaxassislik"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="avatars/%Y/%m/", verbose_name="Rasm"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi",
                "verbose_name_plural": "Foydalanuvchilar",
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", apps.accounts.models.UserManager()),
                ("all_objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("administrator", "Administrator"),
                            ("director", "Direktor"),
                            ("chief_doctor", "Bosh shifokor"),
                            ("reception", "Registratura"),
                            ("doctor", "Shifokor"),
                            ("nurse", "Hamshira"),
                            ("ward_nurse", "Palata hamshirasi"),
                            ("lab", "Laboratoriya"),
                            ("radiology", "Radiologiya"),
                            ("pharmacy", "Farmatsevt"),
                            ("warehouse", "Ombor mudiri"),
                            ("cashier", "Kassir"),
                            ("accountant", "Buxgalter"),
                            ("surgery_admin", "Jarrohlik bo'limi administratori"),
                            ("surgeon", "Jarroh shifokor"),
                            ("sterilization", "Sterilizatsiya (Avtoklav)"),
                            ("auditor", "Auditor (faqat ko'rish)"),
                            ("viewer", "Viewer (faqat ko'rish)"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="Kod",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nomi")),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "is_read_only",
                    models.BooleanField(
                        default=False,
                        help_text="Belgilansa bu roldagi userlar hech narsani o'zgartira olmaydi.",
                        verbose_name="Faqat ko'rish",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="his_roles",
                        to="auth.permission",
                        verbose_name="Huquqlar",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Rollar",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="accounts.role",
                verbose_name="Rol",
            ),
        ),
    ]
