# Generated by Django 5.2.17 on 2026-08-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ambulatory',
            field=models.BooleanField(default=False, help_text='Belgilansa, registraturada shu shifokorga bemor yozdirish mumkin.', verbose_name='Ambulator qabul qiladi'),
        ),
    ]
