# Generated by Django 5.2.17 on 2026-08-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_backfill_is_ambulatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_roles',
            field=models.ManyToManyField(blank=True, help_text="Asosiy roldan tashqari ochiladigan bo'limlar.", related_name='extra_users', to='accounts.role', verbose_name="Qo'shimcha rollar"),
        ),
    ]
