# Generated by Django 5.2.17 on 2026-08-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_extra_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('administrator', 'Registrator'), ('director', 'Direktor'), ('chief_doctor', 'Bosh shifokor'), ('reception', 'Registratura'), ('doctor', 'Shifokor'), ('nurse', 'Hamshira'), ('ward_nurse', 'Palata hamshirasi'), ('lab', 'Laboratoriya'), ('radiology', 'Radiologiya'), ('warehouse', 'Ombor mudiri'), ('cashier', 'Kassir'), ('accountant', 'Buxgalter'), ('surgery_admin', "Jarrohlik bo'limi administratori"), ('surgeon', 'Jarroh shifokor'), ('anesthesiologist', 'Anesteziolog'), ('operating_nurse', 'Operatsion hamshira'), ('sterilization', 'Sterilizatsiya (Avtoklav)'), ('tablo', 'Navbat tablosi (Display)'), ('auditor', "Auditor (faqat ko'rish)"), ('viewer', "Viewer (faqat ko'rish)")], max_length=32, unique=True, verbose_name='Kod'),
        ),
    ]
