# Generated by Django 5.2.16 on 2026-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('service', 'Xizmat (Shifokor, Tahlil)'), ('medicine', 'Dori-darmon'), ('inpatient', 'Statsionar (Palata, Hamroh)'), ('surgery', 'Jarrohlik amaliyoti'), ('other', 'Boshqa')], default='service', max_length=20, verbose_name='Turi'),
        ),
    ]
