# Generated by Django 5.2.16 on 2026-07-24 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoiceitem_item_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name="Qulflangan (o'zgarmas)"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qulflangan vaqt'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Qulflagan xodim'),
        ),
    ]
