# Generated by Django 5.2.17 on 2026-08-09 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_doctorshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqt"),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_items', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qildi (kassir)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='payment_mode',
            field=models.CharField(choices=[('prepaid', "Oldindan to'lanadi"), ('postpaid', 'Kassaga (yakunda)')], db_index=True, default='postpaid', max_length=20, verbose_name="To'lov tartibi"),
        ),
    ]
