# Generated by Django 5.2.17 on 2026-08-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoiceitem_paid_at_invoiceitem_paid_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='price_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name="To'g'rilangan narxlar"),
        ),
    ]
