# Generated by Django 6.0.7 on 2026-07-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nomi"),
                ),
                ("value", models.BigIntegerField(default=0, verbose_name="Qiymat")),
            ],
            options={
                "verbose_name": "Raqam ketma-ketligi",
                "verbose_name_plural": "Raqam ketma-ketliklari",
            },
        ),
    ]
