# Generated by Django 6.0.7 on 2026-07-16 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("clinic_registration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=20, verbose_name="Kravat raqami"),
                ),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Bemor uchun kunlik narxi",
                    ),
                ),
                (
                    "companion_price_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Hamroh uchun kunlik narxi",
                    ),
                ),
                (
                    "is_occupied",
                    models.BooleanField(default=False, verbose_name="Bandmi?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kravat",
                "verbose_name_plural": "Kravatlar",
                "ordering": ["room", "number"],
            },
        ),
        migrations.CreateModel(
            name="DoctorPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Qabul narxi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faolmi?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_price",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Shifokor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shifokor qabul narxi",
                "verbose_name_plural": "Shifokor qabul narxlari",
                "ordering": ["doctor__last_name"],
            },
        ),
        migrations.CreateModel(
            name="DoctorPriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Eski narx",
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Yangi narx",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirdi",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Shifokor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Narx o'zgarishi",
                "verbose_name_plural": "Narx o'zgarishlari tarixi",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InpatientStay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "is_companion",
                    models.BooleanField(default=False, verbose_name="Hamrohmi?"),
                ),
                (
                    "companion_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Hamroh ismi"
                    ),
                ),
                (
                    "admission_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yotqizilgan vaqt"
                    ),
                ),
                (
                    "discharge_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Javob berilgan vaqt"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Yotibdi (Faol)"),
                            ("discharged", "Javob berilgan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_days",
                    models.IntegerField(default=0, verbose_name="Kunlar soni"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Jami summa",
                    ),
                ),
                (
                    "assigned_nurse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_patients",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mas'ul hamshira",
                    ),
                ),
                (
                    "bed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stays",
                        to="clinical.bed",
                        verbose_name="Kravat",
                    ),
                ),
                (
                    "companion_bed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companion_stays",
                        to="clinical.bed",
                        verbose_name="Hamroh kravati",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inpatient_stays",
                        to="clinic_registration.visit",
                        verbose_name="Asosiy qabul",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stasionar yotish",
                "verbose_name_plural": "Stasionar yotishlar",
                "ordering": ["-admission_date"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Xona raqami/nomi"),
                ),
                ("floor", models.IntegerField(default=1, verbose_name="Qavat")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faolmi?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Palata",
                "verbose_name_plural": "Palatalar",
                "ordering": ["floor", "name"],
            },
        ),
        migrations.AddField(
            model_name="bed",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beds",
                to="clinical.room",
                verbose_name="Xona",
            ),
        ),
        migrations.CreateModel(
            name="ServiceCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Xizmat nomi"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Narxi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faolmi?"),
                ),
                (
                    "allowed_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="accounts.role",
                        verbose_name="Bajaruvchi rol",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat",
                "verbose_name_plural": "Xizmatlar katalogi",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Kutmoqda (To'lanmagan)"),
                            ("paid", "To'langan"),
                            ("in_progress", "Bajarilmoqda"),
                            ("completed", "Yakunlangan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "result_text",
                    models.TextField(blank=True, verbose_name="Natija (Xulosa)"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_services",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bajardi",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="clinical.servicecatalog",
                        verbose_name="Xizmat",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_orders",
                        to="clinic_registration.visit",
                        verbose_name="Asosiy Qabul",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xizmat buyurtmasi",
                "verbose_name_plural": "Xizmat buyurtmalari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurgeryType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Operatsiya nomi"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Narxi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faolmi?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operatsiya turi",
                "verbose_name_plural": "Operatsiya turlari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SurgicalItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nomi")),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("nabor", "Jarrohlik nabori"),
                            ("mechanical_valve", "Mexanik klapan"),
                            ("synthetic_valve", "Sintetik klapan"),
                            ("implant", "Boshqa implant/uskuna"),
                        ],
                        max_length=50,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Tozalandi / Tayyor"),
                            ("in_use", "Operatsiyada"),
                            ("used", "Ishlatilgan / Ifloslangan"),
                        ],
                        default="ready",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Seriya raqami"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jarrohlik uskunasi",
                "verbose_name_plural": "Jarrohlik uskunalari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SurgerySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(verbose_name="Belgilangan vaqt"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Rejalashtirilgan"),
                            ("in_progress", "Bajarilmoqda"),
                            ("completed", "Yakunlangan"),
                            ("cancelled", "Bekor qilingan"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Izoh/Xulosa")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "surgeon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="performed_surgeries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Jarroh",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgeries",
                        to="clinic_registration.visit",
                        verbose_name="Asosiy qabul",
                    ),
                ),
                (
                    "surgery_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="clinical.surgerytype",
                        verbose_name="Operatsiya turi",
                    ),
                ),
                (
                    "items_used",
                    models.ManyToManyField(
                        blank=True,
                        related_name="surgeries",
                        to="clinical.surgicalitem",
                        verbose_name="Ishlatilgan uskunalar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operatsiya jadvali",
                "verbose_name_plural": "Operatsiya jadvallari",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="SurgicalItemHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Ishlatilgan vaqt"
                    ),
                ),
                ("action", models.CharField(max_length=100, verbose_name="Harakat")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="clinical.surgicalitem",
                    ),
                ),
                (
                    "surgery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_history",
                        to="clinical.surgeryschedule",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uskuna tarixi",
                "verbose_name_plural": "Uskuna tarixlari",
                "ordering": ["-used_at"],
            },
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                ("complaint", models.TextField(blank=True, verbose_name="Shikoyat")),
                (
                    "anamnesis",
                    models.TextField(
                        blank=True, verbose_name="Kasallik tarixi (Anamnez)"
                    ),
                ),
                (
                    "objective_status",
                    models.TextField(blank=True, verbose_name="Obyektiv holat"),
                ),
                ("diagnosis", models.TextField(verbose_name="Yakuniy tashxis")),
                (
                    "prescription",
                    models.TextField(
                        blank=True, verbose_name="Dori-darmonlar (Retsept)"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="Tavsiyalar"),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Qabul narxi (o'sha paytdagi)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Shifokor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="clinic_registration.visit",
                        verbose_name="Qabul",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shifokor xulosasi",
                "verbose_name_plural": "Shifokor xulosalari",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("visit", "doctor"),
                        name="uniq_consultation_per_visit_doctor",
                    )
                ],
            },
        ),
    ]
