# Generated by Django 5.2.16 on 2026-07-16 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0003_surgeryschedule_actual_price_surgerytypepricehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="surgicalitemhistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kim o'zgartirdi",
            ),
        ),
        migrations.AlterField(
            model_name="surgicalitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready", "Tozalandi / Tayyor"),
                    ("in_use", "Operatsiyada"),
                    ("used", "Ishlatilgan / Ifloslangan"),
                ],
                default="used",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="surgicalitemhistory",
            name="surgery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="item_history",
                to="clinical.surgeryschedule",
            ),
        ),
        migrations.AlterField(
            model_name="surgicalitemhistory",
            name="used_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Vaqti"),
        ),
    ]
