# Generated by Django 5.2.16 on 2026-07-17 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_surgicalitemhistory_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='package_price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Paketli (dori ichida) kunlik narx'),
        ),
        migrations.AddField(
            model_name='inpatientstay',
            name='doc_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_stays', to=settings.AUTH_USER_MODEL, verbose_name='Hujjatlashtirish hamshirasi'),
        ),
        migrations.AddField(
            model_name='inpatientstay',
            name='patient_signature',
            field=models.TextField(blank=True, verbose_name='Bemor imzosi (rasm, base64)'),
        ),
        migrations.AddField(
            model_name='inpatientstay',
            name='procedure_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_stays', to=settings.AUTH_USER_MODEL, verbose_name='Ukol/muolaja hamshirasi'),
        ),
        migrations.AddField(
            model_name='inpatientstay',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Imzolangan vaqt'),
        ),
        migrations.AddField(
            model_name='inpatientstay',
            name='stay_type',
            field=models.CharField(choices=[('standard', "Oddiy (dori alohida to'lanadi)"), ('package', 'Paketli (dori narxi yotish ichida)')], default='standard', max_length=20, verbose_name='Statsionar turi'),
        ),
        migrations.CreateModel(
            name='ProcedureRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('category', models.CharField(choices=[('injection', 'Ukol'), ('procedure', 'Muolaja'), ('surgery', 'Operatsiyada qatnashish'), ('analysis', 'Analiz olish'), ('other', 'Boshqa')], default='injection', max_length=20, verbose_name='Turi')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi (dori/muolaja/operatsiya)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Izoh (doza, natija va h.k.)')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Bajarilgan vaqt')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_records', to=settings.AUTH_USER_MODEL, verbose_name='Hamshira')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_records', to='clinical.inpatientstay', verbose_name='Statsionar yotish')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Muolaja qaydi (hamshira)',
                'verbose_name_plural': 'Muolaja qaydlari (hamshira)',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='StayChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('category', models.CharField(choices=[('medicine', 'Dori berish'), ('injection', 'Ukol'), ('procedure', 'Muolaja'), ('analysis', 'Analiz/Tekshiruv'), ('surgery', 'Operatsiya'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi/tavsifi')),
                ('reference_id', models.UUIDField(blank=True, null=True, verbose_name='Manba ID')),
                ('is_done', models.BooleanField(default=False, verbose_name='Bajarildimi? (+)')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_marks', to=settings.AUTH_USER_MODEL, verbose_name='Belgiladi')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='clinical.inpatientstay', verbose_name='Statsionar yotish')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Hujjat bandi (statsionar)',
                'verbose_name_plural': 'Hujjat bandlari (statsionar)',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('arrival_condition', models.TextField(blank=True, verbose_name='Bemor ahvoli (qanday keldi)')),
                ('performed_actions', models.TextField(blank=True, verbose_name='Nimalar qilindi (jarayon tavsifi)')),
                ('medications', models.TextField(blank=True, verbose_name='Yozilgan/berilgan dorilar')),
                ('injections', models.TextField(blank=True, verbose_name='Qilingan ukollar')),
                ('anesthesia', models.TextField(blank=True, verbose_name='Narkoz (turi, dozasi, anesteziolog)')),
                ('consumables', models.TextField(blank=True, verbose_name='Sarflangan materiallar (perchatka, bint va h.k.)')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha izohlar")),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_reports', to=settings.AUTH_USER_MODEL, verbose_name="To'ldirdi")),
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='clinical.surgeryschedule', verbose_name='Operatsiya')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Operatsiya bayonnomasi',
                'verbose_name_plural': 'Operatsiya bayonnomalari',
            },
        ),
        migrations.CreateModel(
            name='ConsultationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('name', models.CharField(max_length=150, verbose_name='Shablon nomi')),
                ('complaint', models.TextField(blank=True, verbose_name='Shikoyat')),
                ('anamnesis', models.TextField(blank=True, verbose_name='Anamnez')),
                ('objective_status', models.TextField(blank=True, verbose_name='Obyektiv holat')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Tashxis')),
                ('prescription', models.TextField(blank=True, verbose_name='Retsept')),
                ('recommendations', models.TextField(blank=True, verbose_name='Tavsiyalar')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_templates', to=settings.AUTH_USER_MODEL, verbose_name='Shifokor')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Tashxis shabloni',
                'verbose_name_plural': 'Tashxis shablonlari',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('doctor', 'name'), name='uniq_template_per_doctor_name')],
            },
        ),
    ]
