# Generated by Django 5.2.16 on 2026-07-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0005_bed_package_price_per_day_inpatientstay_doc_nurse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="report_html",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tibbiy xulosa (HTML)"
            ),
        ),
        migrations.AddField(
            model_name="consultationtemplate",
            name="report_html",
            field=models.TextField(
                blank=True, null=True, verbose_name="Shablon matni (HTML)"
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="diagnosis",
            field=models.TextField(
                blank=True, null=True, verbose_name="Yakuniy tashxis"
            ),
        ),
    ]
