# Generated by Django 5.2.16 on 2026-07-17 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0006_consultation_report_html_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inpatientstay",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctor_stays",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mas'ul shifokor",
            ),
        ),
    ]
