# Generated by Django 5.2.16 on 2026-07-20 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0009_backfill_price_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryschedule',
            name='anesthesia_exam_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ko'rik vaqti"),
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='anesthesia_exam_note',
            field=models.TextField(blank=True, verbose_name="Anesteziologik ko'rik natijasi"),
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='anesthesiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anesthetized_surgeries', to=settings.AUTH_USER_MODEL, verbose_name='Anesteziolog'),
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_surgeries', to=settings.AUTH_USER_MODEL, verbose_name='Operatsion asistent'),
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Operatsiya tugadi'),
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='operating_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursed_surgeries', to=settings.AUTH_USER_MODEL, verbose_name='Operatsion hamshira'),
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='preparation_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tayyorlash vaqti'),
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='preparation_note',
            field=models.TextField(blank=True, verbose_name='Tayyorlash bayoni (xona/asbob)'),
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='room_prepared',
            field=models.BooleanField(default=False, verbose_name='Xona tayyorlandi'),
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='stage',
            field=models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('anesthesia_exam', "1. Anesteziologik ko'rik / punksiya"), ('preparation', '2. Operatsiyaga tayyorlash'), ('operating', '3. Operatsiya jarayoni (protokol)'), ('finished', 'Yakunlandi')], default='scheduled', max_length=20, verbose_name='Jarayon bosqichi'),
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Operatsiya boshlandi'),
        ),
        migrations.CreateModel(
            name='AnesthesiaRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('status', models.CharField(choices=[('requested', 'Zayavka berildi'), ('sent', 'Yuborildi')], default='requested', max_length=20, verbose_name='Holati')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anesthesia_requests_made', to=settings.AUTH_USER_MODEL, verbose_name="So'ragan")),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anesthesia_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Yuborgan (anesteziolog)')),
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anesthesia_request', to='clinical.surgeryschedule', verbose_name='Operatsiya')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Anesteziolog zayavkasi',
                'verbose_name_plural': 'Anesteziolog zayavkalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnesthesiaStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('unit', models.CharField(default='dona', max_length=30, verbose_name="O'lchov birligi")),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qoldiq soni')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sotish narxi (birlik)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Anesteziolog ombori (mahsulot)',
                'verbose_name_plural': 'Anesteziolog ombori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnesthesiaRequestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Soni')),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0, help_text="Yuborilgan paytdagi sotish narxi — keyin o'zgarsa ham bu o'zgarmaydi.", max_digits=12, verbose_name='Narx (yuborilgandagi)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.anesthesiarequest', verbose_name='Zayavka')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='clinical.anesthesiastock', verbose_name='Ombor mahsuloti')),
            ],
            options={
                'verbose_name': 'Zayavka qatori',
                'verbose_name_plural': 'Zayavka qatorlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NurseUsageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('name', models.CharField(max_length=200, verbose_name='Anjom / material nomi')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Soni')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Narxi (birlik, sotish)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_usage_items', to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_usages', to='clinical.surgeryschedule', verbose_name='Operatsiya')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Hamshira ishlatgan anjom',
                'verbose_name_plural': 'Hamshira ishlatgan anjomlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Xona nomi')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Operatsion xona',
                'verbose_name_plural': 'Operatsion xonalar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='surgeryschedule',
            name='operating_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='clinical.operatingroom', verbose_name='Operatsion xona'),
        ),
        migrations.CreateModel(
            name='SurgeryVitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('blood_pressure', models.CharField(blank=True, max_length=20, verbose_name='Qon bosimi (davleniye)')),
                ('pulse', models.PositiveIntegerField(blank=True, null=True, verbose_name='Puls (impuls)')),
                ('spo2', models.PositiveIntegerField(blank=True, null=True, verbose_name='SpO₂ (%)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Qilingan ish / dori')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_vitals', to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='clinical.surgeryschedule', verbose_name='Operatsiya')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': "Operatsiya ko'rsatkichi",
                'verbose_name_plural': "Operatsiya ko'rsatkichlari (protokol)",
                'ordering': ['recorded_at'],
            },
        ),
    ]
