# Generated by Django 5.2.16 on 2026-07-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0011_anesthesiarequest_pre_op_evaluation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nurseusageitem",
            name="name",
        ),
        migrations.AddField(
            model_name="nurseusageitem",
            name="stock",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nurse_usages",
                to="clinical.anesthesiastock",
                verbose_name="Anesteziolog omboridan anjom",
            ),
        ),
    ]
