# Generated by Django 5.2.16 on 2026-07-20 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0012_remove_nurseusageitem_name_nurseusageitem_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "role__code__in": ["doctor", "chief_doctor", "surgeon"]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mas'ul shifokor",
            ),
        ),
    ]
