# Generated by Django 5.2.16 on 2026-07-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0013_room_assigned_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryschedule',
            name='anesthesia_type',
            field=models.CharField(blank=True, choices=[('general', 'Umumiy narkoz (intubatsiya)'), ('spinal', 'Spinal / epidural'), ('local', "Mahalliy og'riqsizlantirish"), ('sedation', 'Sedatsiya (yuza uyqu)')], max_length=20, verbose_name='Narkoz turi'),
        ),
    ]
