# Generated by Django 5.2.16 on 2026-07-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0014_surgeryschedule_anesthesia_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='anesthesiarequestitem',
            name='is_extra',
            field=models.BooleanField(default=False, help_text="Boshida olib kelinganidan tashqari, jarayonda qo'shimcha olingan.", verbose_name="Qo'shimcha (operatsiya davomida olingan)"),
        ),
        migrations.AddField(
            model_name='anesthesiarequestitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ishlatilmay omborga qaytarilgan miqdor — hisobdan chiqadi.', max_digits=12, verbose_name='Qaytarilgan soni'),
        ),
        migrations.AddField(
            model_name='nurseusageitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ishlatilmay omborga qaytarilgan miqdor — hisobdan chiqadi.', max_digits=12, verbose_name='Qaytarilgan soni'),
        ),
    ]
