# Generated by Django 5.2.16 on 2026-07-23 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0015_anesthesiarequestitem_is_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalitem',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_items', to='clinical.operatingroom', verbose_name='Joriy xona'),
        ),
    ]
