# Generated by Django 5.2.16 on 2026-07-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0016_surgicalitem_current_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryschedule',
            name='postop_recommendations',
            field=models.TextField(blank=True, verbose_name="Operatsiyadan keyingi tavsiyalar (bo'lim hamshirasi)"),
        ),
        migrations.AddField(
            model_name='surgerytype',
            name='kind',
            field=models.CharField(choices=[('open', 'Ochiq operatsiya'), ('endoscopic', 'Endoskopik operatsiya')], default='open', help_text='Ochiq: avtoklav anjomlar + belyo. Endoskopik: rastvor anjomlar + belyo.', max_length=20, verbose_name='Operatsiya usuli'),
        ),
        migrations.AddField(
            model_name='surgicalitem',
            name='steril_method',
            field=models.CharField(choices=[('autoclave', 'Avtoklav'), ('solution', 'Rastvor (eritma) sterilizatsiya')], default='autoclave', help_text='Belyo va ochiq operatsiya anjomlari — avtoklav; endoskopik anjomlar — rastvor.', max_length=20, verbose_name='Sterilizatsiya usuli'),
        ),
        migrations.AlterField(
            model_name='surgeryvitals',
            name='recorded_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='surgicalitem',
            name='item_type',
            field=models.CharField(choices=[('nabor', 'Jarrohlik nabori'), ('mechanical_valve', 'Mexanik klapan'), ('synthetic_valve', 'Sintetik klapan'), ('implant', 'Boshqa implant/uskuna'), ('linen', 'Belyo (material biks)'), ('endo_instrument', 'Endoskopik anjom')], max_length=50, verbose_name='Turi'),
        ),
    ]
