# Generated by Django 5.2.16 on 2026-07-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0017_surgeryschedule_postop_recommendations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgicalitem',
            name='item_type',
            field=models.CharField(choices=[('nabor', 'Jarrohlik nabori'), ('mechanical_valve', 'Mexanik klapan'), ('synthetic_valve', 'Sintetik klapan'), ('implant', 'Boshqa implant/uskuna'), ('linen', 'Belyo (material biks)'), ('endo_instrument', 'Endoskopik anjom'), ('aptechka', "Aptechka (shoshilinch dori to'plami)")], max_length=50, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='surgicalitem',
            name='steril_method',
            field=models.CharField(choices=[('autoclave', 'Avtoklav'), ('solution', 'Rastvor (eritma) sterilizatsiya'), ('none', 'Sterilizatsiya shart emas')], default='autoclave', help_text='Belyo va ochiq operatsiya anjomlari — avtoklav; endoskopik anjomlar — rastvor.', max_length=20, verbose_name='Sterilizatsiya usuli'),
        ),
    ]
