# Generated by Django 5.2.16 on 2026-07-26 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0020_consultation_is_locked_consultation_locked_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anesthesiastock",
            name="is_psychotropic",
            field=models.BooleanField(
                default=False,
                help_text="Psixotrop/narkotik dori-darmon (faqat Anesteziolog zayavka qiladi).",
                verbose_name="Psixotrop dori",
            ),
        ),
        migrations.AddField(
            model_name="surgeryschedule",
            name="patient_prep_note",
            field=models.TextField(blank=True, verbose_name="Bemor tayyorlash bayoni"),
        ),
        migrations.AddField(
            model_name="surgeryschedule",
            name="patient_prepared",
            field=models.BooleanField(default=False, verbose_name="Bemor tayyorlandi"),
        ),
        migrations.AddField(
            model_name="surgeryschedule",
            name="patient_prepared_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bemor tayyorlangan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="surgeryschedule",
            name="stage",
            field=models.CharField(
                choices=[
                    ("scheduled", "Rejalashtirilgan"),
                    ("patient_prep", "1. Bemorni tayyorlash (Bo'lim hamshirasi)"),
                    ("anesthesia_exam", "2. Anesteziologik ko'rik / punksiya"),
                    ("preparation", "3. Operatsiyaga tayyorlash (Xona)"),
                    ("operating", "4. Operatsiya jarayoni (protokol)"),
                    ("finished", "Yakunlandi"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="Jarayon bosqichi",
            ),
        ),
        migrations.CreateModel(
            name="AnesthesiaStockPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="O'ram nomi (Blok, Pochka...)"
                    ),
                ),
                (
                    "quantity_in_base_unit",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Ichida nechta asosiy birlik bor?",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="clinical.anesthesiastock",
                        verbose_name="Ombor mahsuloti",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anesteziolog ombori qadog'i",
                "verbose_name_plural": "Anesteziolog ombori qadoqlari",
                "ordering": ["-quantity_in_base_unit"],
            },
        ),
        migrations.CreateModel(
            name="RoomLeftover",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Qoldiq soni",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "from_surgery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leftovers_created",
                        to="clinical.surgeryschedule",
                        verbose_name="Qaysi operatsiyadan qolgan",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leftovers",
                        to="clinical.operatingroom",
                        verbose_name="Operatsion xona",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="room_leftovers",
                        to="clinical.anesthesiastock",
                        verbose_name="Mahsulot",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xona qoldig'i",
                "verbose_name_plural": "Xona qoldiqlari",
                "ordering": ["room", "stock"],
            },
        ),
    ]
