# Generated by Django 5.2.16 on 2026-07-29 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0022_ambulatoryroom"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ambulatoryroom",
            name="doctor",
        ),
        migrations.AddField(
            model_name="ambulatoryroom",
            name="doctors",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role__code__in": ["doctor", "chief_doctor"]},
                related_name="ambulatory_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mas'ul shifokorlar",
            ),
        ),
    ]
