# Generated by Django 5.2.16 on 2026-07-30 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0024_alter_ambulatoryroom_doctors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="surgeryschedule",
            name="ward_nurse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ward_nursed_surgeries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Bo'lim hamshirasi",
            ),
        ),
    ]
