# Generated by Django 5.2.16 on 2026-08-01 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0025_surgeryschedule_ward_nurse'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surgicalitemhistory',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgical_item_uses', to='patients.patient', verbose_name='Bemor'),
        ),
        migrations.AddField(
            model_name='surgicalitemhistory',
            name='patient_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bemor (nusxa)'),
        ),
        migrations.AddField(
            model_name='surgicalitemhistory',
            name='room_snapshot',
            field=models.CharField(blank=True, max_length=120, verbose_name='Operatsion xona (nusxa)'),
        ),
        migrations.AddField(
            model_name='surgicalitemhistory',
            name='surgeon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgical_item_uses', to=settings.AUTH_USER_MODEL, verbose_name='Jarroh (boshchiligida)'),
        ),
        migrations.AddField(
            model_name='surgicalitemhistory',
            name='surgeon_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='Jarroh (nusxa)'),
        ),
        migrations.AddField(
            model_name='surgicalitemhistory',
            name='surgery_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='Operatsiya (nusxa)'),
        ),
        migrations.AddIndex(
            model_name='surgicalitemhistory',
            index=models.Index(fields=['item', '-used_at'], name='clinical_su_item_id_07a6b2_idx'),
        ),
    ]
