# Generated by Django 5.2.16 on 2026-08-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0027_backfill_item_history_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatalog',
            name='responsible_staff',
            field=models.ForeignKey(blank=True, help_text="Shu xizmatni odatda bajaradigan xodim. Bo'sh qoldirilsa — rol bo'yicha kim bo'sh bo'lsa.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_services', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul xodim"),
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='clinical.ambulatoryroom', verbose_name='Kabinet (qaysi xona)'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan vaqt'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qildi'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='defer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Necha marta kechiktirilgan'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='deferred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kechiktirilgan vaqt'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='deferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Kechiktirdi'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='deferred_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kechiktirish sababi'),
        ),
    ]
