# Generated by Django 5.2.16 on 2026-08-03 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0028_servicecatalog_responsible_staff_servicecatalog_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='call_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Necha marta chaqirilgan'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chaqirilgan vaqt'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='called_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Chaqirdi'),
        ),
    ]
