# Generated by Django 5.2.17 on 2026-08-09 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_role_code'),
        ('clinical', '0029_serviceorder_call_count_serviceorder_called_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecatalog',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar katalogi'},
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='result_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Natija vaqti'),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('name', models.CharField(max_length=150, verbose_name='Guruh nomi')),
                ('kind', models.CharField(choices=[('lab', 'Laboratoriya'), ('diagnostic', 'Instrumental diagnostika'), ('other', 'Boshqa')], default='lab', help_text='Modalda qaysi tugma ostida chiqishini belgilaydi.', max_length=20, verbose_name='Turi')),
                ('button_label', models.CharField(blank=True, help_text="Faqat yuqori darajadagi guruhlarda. Bo'sh bo'lsa nom ishlatiladi.", max_length=50, verbose_name='Tugma yozuvi')),
                ('icon', models.CharField(blank=True, max_length=8, verbose_name='Belgi (emoji)')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('default_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_service_categories', to='accounts.role', verbose_name='Standart bajaruvchi rol')),
                ('default_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_service_categories', to='clinical.ambulatoryroom', verbose_name='Standart kabinet')),
                ('default_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_service_categories', to=settings.AUTH_USER_MODEL, verbose_name="Standart mas'ul xodim")),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='clinical.servicecategory', verbose_name='Yuqori guruh')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Tekshiruvlar guruhi',
                'verbose_name_plural': 'Tekshiruvlar guruhlari',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='servicecatalog',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa tekshiruv tayinlash modalida ko'rinmaydi (masalan «Shifokor ko'rigi» kabi xizmatlar).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='clinical.servicecategory', verbose_name='Guruh'),
        ),
        migrations.CreateModel(
            name='ServiceResultRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('name', models.CharField(max_length=150, verbose_name="Ko'rsatkich")),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Natija')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name="O'lchov birligi")),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Norma')),
                ('is_abnormal', models.BooleanField(default=False, help_text="Blankda qalin va rangli ko'rsatiladi.", verbose_name='Normadan chetda')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Tartib')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_rows', to='clinical.serviceorder', verbose_name='Tekshiruv')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': "Natija ko'rsatkichi",
                'verbose_name_plural': "Natija ko'rsatkichlari",
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResultTemplateRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('name', models.CharField(max_length=150, verbose_name="Ko'rsatkich")),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name="O'lchov birligi")),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Norma')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Tartib')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_template', to='clinical.servicecatalog', verbose_name='Tekshiruv')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Natija shabloni qatori',
                'verbose_name_plural': 'Natija shabloni qatorlari',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('service', 'name'), name='uniq_template_row_per_service')],
            },
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_category_name_per_parent'),
        ),
    ]
