# Generated by Django 5.2.17 on 2026-08-09 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_registration', '0001_initial'),
        ('clinical', '0031_seed_service_categories'),
        ('patients', '0002_patient_birth_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('is_locked', models.BooleanField(default=False, verbose_name="Qulflangan (o'zgarmas)")),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Qulflangan vaqt')),
                ('document_type', models.CharField(choices=[('jshshir', 'JSHSHIR'), ('metrika', "Metrika (tug'ilganlik guvohnomasi)")], default='jshshir', max_length=20, verbose_name='Hujjat turi')),
                ('document_number', models.CharField(blank=True, max_length=30, verbose_name='Hujjat raqami')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='Murojaat epizodi (kasallik sababi)')),
                ('purpose', models.CharField(choices=[('treatment', 'Davolash uchun'), ('surgery', 'Operatsiya uchun'), ('other', 'Boshqa')], default='treatment', max_length=20, verbose_name='Yotqizish maqsadi')),
                ('purpose_note', models.CharField(blank=True, max_length=255, verbose_name='Maqsad izohi')),
                ('with_primary_exam', models.BooleanField(default=True, verbose_name="Birlamchi ko'rik bilan")),
                ('department', models.CharField(blank=True, max_length=150, verbose_name="Bo'lim")),
                ('complaints', models.TextField(blank=True, verbose_name='Shikoyatlar')),
                ('anamnesis_morbi', models.TextField(blank=True, verbose_name='Kasallik tarixi (Anamnesis morbi)')),
                ('anamnesis_vitae', models.TextField(blank=True, verbose_name='Hayot anamnezi (Anamnesis vitae)')),
                ('status_localis', models.TextField(blank=True, verbose_name='Mahalliy holat (Status localis)')),
                ('epid_anamnesis', models.TextField(blank=True, verbose_name='Epidemiologik anamnez')),
                ('status_praesens', models.TextField(blank=True, verbose_name='Obyektiv holat (Status praesens)')),
                ('allergo_anamnesis', models.TextField(blank=True, verbose_name='Allergoanamnez')),
                ('neuro_status', models.TextField(blank=True, verbose_name='Nevrologik holati')),
                ('clinical_diagnosis', models.TextField(blank=True, verbose_name='Klinik tashxis')),
                ('status', models.CharField(choices=[('draft', 'Rasmiylashtirilmoqda'), ('sent', 'Qabulxonaga yuborildi'), ('admitted', 'Yotqizildi'), ('discharged', 'Vipiska berildi'), ('cancelled', 'Bekor qilindi')], db_index=True, default='draft', max_length=20, verbose_name='Holati')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabulxonaga yuborilgan')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='Bekor qilish sababi')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Qulflagan xodim')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='patients.patient', verbose_name='Bemor')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referred_episodes', to=settings.AUTH_USER_MODEL, verbose_name="Yo'llagan shifokor")),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='clinical.room', verbose_name='Palata')),
                ('stay', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode', to='clinical.inpatientstay', verbose_name='Yotish yozuvi')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='clinic_registration.visit', verbose_name='Ambulator qabul')),
            ],
            options={
                'verbose_name': 'Statsionar epizodi',
                'verbose_name_plural': 'Statsionar epizodlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=300, verbose_name='Tashxis nomi')),
                ('chapter', models.CharField(blank=True, max_length=150, verbose_name="Bo'lim")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'MKB-10 kodi',
                'verbose_name_plural': 'MKB-10 kodlari',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('free_text', models.CharField(blank=True, max_length=300, verbose_name='Tashxis (matn)')),
                ('stage', models.CharField(choices=[('preliminary', 'Dastlabki tashxis'), ('final', 'Yakuniy tashxis')], default='preliminary', max_length=20, verbose_name='Tashxis turi')),
                ('kind', models.CharField(choices=[('main', 'Asosiy'), ('concomitant', 'Hamroh'), ('complication', 'Asorat'), ('background', 'Fon'), ('competing', 'Raqobatdosh')], default='main', max_length=20, verbose_name='Xili')),
                ('course', models.CharField(choices=[('unspecified', 'Belgilanmagan'), ('acute', "O'tkir"), ('subacute', "O'tkir osti"), ('first_chronic', 'Hayotda birinchi marta surunkali kasallik aniqlandi'), ('chronic', 'Surunkali')], default='unspecified', max_length=20, verbose_name='Kasallik kechishi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinical.admissionepisode', verbose_name='Epizod')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
                ('icd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='clinical.icd10code', verbose_name='MKB-10')),
            ],
            options={
                'verbose_name': 'Epizod tashxisi',
                'verbose_name_plural': 'Epizod tashxislari',
                'ordering': ['kind', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='admissionepisode',
            index=models.Index(fields=['patient', 'status'], name='clinical_ad_patient_632a6a_idx'),
        ),
    ]
