# Generated by Django 5.2.17 on 2026-08-09 11:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0034_endoscopy_fixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('is_locked', models.BooleanField(default=False, verbose_name="Qulflangan (o'zgarmas)")),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Qulflangan vaqt')),
                ('discharged_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Chiqarilgan vaqt')),
                ('outcome', models.CharField(choices=[('recovered', "Sog'aydi"), ('improved', 'Yaxshilandi'), ('unchanged', "O'zgarishsiz"), ('worsened', 'Yomonlashdi'), ('transferred', "Boshqa muassasaga o'tkazildi"), ('died', 'Vafot etdi')], default='improved', max_length=20, verbose_name='Davolash natijasi')),
                ('work_capacity', models.CharField(choices=[('fit', 'Mehnatga layoqatli'), ('sick_leave', 'Kasallik varaqasi berildi'), ('light', 'Yengil mehnatga tavsiya'), ('unfit', 'Mehnatga layoqatsiz'), ('n_a', 'Tegishli emas')], default='n_a', max_length=20, verbose_name='Mehnat qobiliyati')),
                ('sick_leave_from', models.DateField(blank=True, null=True, verbose_name='Kasallik varaqasi (dan)')),
                ('sick_leave_to', models.DateField(blank=True, null=True, verbose_name='Kasallik varaqasi (gacha)')),
                ('treatment_given', models.TextField(blank=True, verbose_name="O'tkazilgan davolash")),
                ('condition_at_discharge', models.TextField(blank=True, verbose_name='Chiqishdagi holati')),
                ('recommendations', models.TextField(blank=True, verbose_name='Tavsiyalar')),
                ('follow_up', models.CharField(blank=True, max_length=255, verbose_name="Nazorat ko'rigi")),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discharge_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Vipiskani yozgan shifokor')),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='clinical.admissionepisode', verbose_name='Epizod')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Qulflagan xodim')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Vipiska',
                'verbose_name_plural': 'Vipiskalar',
                'ordering': ['-discharged_at'],
            },
        ),
    ]
