# Generated by Django 5.2.17 on 2026-08-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0036_dischargesummary_selected_order_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='item_texts',
            field=models.JSONField(blank=True, default=dict, verbose_name="Vipiskadagi matnlar (element bo'yicha)"),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='selected_diagnosis_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Tanlangan tashxislar'),
        ),
    ]
