# Generated by Django 5.2.17 on 2026-08-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0038_service_group_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionepisode',
            name='selected_order_ids',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Vipiskaga tanlangan tekshiruvlar'),
        ),
    ]
