# Generated by Django 5.2.17 on 2026-08-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0039_admissionepisode_selected_order_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='selected_surgery_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Tanlangan operatsiyalar'),
        ),
    ]
