# Generated by Django 5.2.17 on 2026-08-14 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0040_dischargesummary_selected_surgery_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgerySupplyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('status', models.CharField(choices=[('draft', 'Tayyorlanmoqda'), ('sent', 'Omborga yuborildi'), ('issued', 'Ombor berdi'), ('rejected', 'Rad etildi')], default='draft', max_length=20, verbose_name='Holati')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Berilgan vaqt')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_supplies_issued', to=settings.AUTH_USER_MODEL, verbose_name='Ombordan bergan')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_supply_requests', to=settings.AUTH_USER_MODEL, verbose_name="So'ragan hamshira")),
                ('surgery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_request', to='clinical.surgeryschedule', verbose_name='Operatsiya')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
            ],
            options={
                'verbose_name': 'Operatsion hamshira zayavkasi',
                'verbose_name_plural': 'Operatsion hamshira zayavkalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurgerySupplyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name="O'chirilgan")),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name="O'chirilgan vaqt")),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name="So'ralgan soni")),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Berilgan soni')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'chirgan")),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgery_supply_items', to='clinical.anesthesiastock', verbose_name='Anesteziolog omboridagi material')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="O'zgartirgan")),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clinical.surgerysupplyrequest', verbose_name='Zayavka')),
            ],
            options={
                'verbose_name': 'Zayavka qatori',
                'verbose_name_plural': 'Zayavka qatorlari',
                'ordering': ['created_at'],
            },
        ),
    ]
