# Generated by Django 5.2.16 on 2026-08-21 04:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinical", "0042_surgerytemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anesthesiastock",
            options={
                "ordering": ["name"],
                "verbose_name": "Umumiy ombor (mahsulot)",
                "verbose_name_plural": "Umumiy ombor",
            },
        ),
        migrations.AlterModelOptions(
            name="anesthesiastockpackage",
            options={
                "ordering": ["-quantity_in_base_unit"],
                "verbose_name": "Umumiy ombor qadog'i",
                "verbose_name_plural": "Umumiy ombor qadoqlari",
            },
        ),
        migrations.AlterField(
            model_name="nurseusageitem",
            name="stock",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nurse_usages",
                to="clinical.anesthesiastock",
                verbose_name="Umumiy ombordan anjom",
            ),
        ),
        migrations.AlterField(
            model_name="surgerysupplyitem",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="surgery_supply_items",
                to="clinical.anesthesiastock",
                verbose_name="Umumiy ombordagi material",
            ),
        ),
        migrations.CreateModel(
            name="HistologyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(max_length=255, verbose_name="Bemor F.I.Sh"),
                ),
                (
                    "jshshir",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="JSHSHIR"
                    ),
                ),
                (
                    "metric_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Metrika (Kasallik tarixi) raqami",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Sana"
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Bo'lim/Xona",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, null=True, verbose_name="Tashxis"),
                ),
                (
                    "material",
                    models.CharField(
                        max_length=255, verbose_name="Olingan to'qima (material)"
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True, null=True, verbose_name="Gistologiya xulosasi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patalogo-gistologik jurnal",
                "verbose_name_plural": "Patalogo-gistologik jurnallar",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MinorSurgeryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(max_length=255, verbose_name="Bemor F.I.Sh"),
                ),
                (
                    "jshshir",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="JSHSHIR"
                    ),
                ),
                (
                    "metric_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Metrika (Kasallik tarixi) raqami",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Sana"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, null=True, verbose_name="Tashxis"),
                ),
                ("surgery_name", models.TextField(verbose_name="Operatsiya nomi")),
                ("surgeon", models.CharField(max_length=255, verbose_name="Jarroh")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kichik operatsiyalar jurnali",
                "verbose_name_plural": "Kichik operatsiyalar jurnallari",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutpatientSurgeryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(max_length=255, verbose_name="Bemor F.I.Sh"),
                ),
                (
                    "jshshir",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="JSHSHIR"
                    ),
                ),
                (
                    "metric_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Metrika (Kasallik tarixi) raqami",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Sana"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, null=True, verbose_name="Tashxis"),
                ),
                (
                    "intervention",
                    models.TextField(verbose_name="O'tkazilgan muolaja/operatsiya"),
                ),
                ("doctor", models.CharField(max_length=255, verbose_name="Shifokor")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ambulator operatsiyalar jurnali",
                "verbose_name_plural": "Ambulator operatsiyalar jurnallari",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SimultaneousSurgeryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(max_length=255, verbose_name="Bemor F.I.Sh"),
                ),
                (
                    "jshshir",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="JSHSHIR"
                    ),
                ),
                (
                    "metric_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Metrika (Kasallik tarixi) raqami",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Sana"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, null=True, verbose_name="Tashxis"),
                ),
                ("primary_surgery", models.TextField(verbose_name="Asosiy operatsiya")),
                (
                    "simultaneous_surgery",
                    models.TextField(verbose_name="Semultant operatsiya"),
                ),
                ("surgeon", models.CharField(max_length=255, verbose_name="Jarroh")),
                (
                    "assistants",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Assistentlar",
                    ),
                ),
                (
                    "anesthesiologist",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Anesteziolog",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Semultant operatsiyalar jurnali",
                "verbose_name_plural": "Semultant operatsiyalar jurnallari",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SterilizationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("dc1_general", "DC-1 (Umumiy)"),
                            ("peroxide_general", "Perekis 3% (Umumiy)"),
                            ("dc1_urology", "DC-1 (Urologiya)"),
                            ("peroxide_urology", "Perekis 3% (Urologiya)"),
                        ],
                        max_length=32,
                        verbose_name="Jurnal turi",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Sana"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        default="Laparoskop va uning tarkibiy qismlari",
                        max_length=255,
                        verbose_name="Uskuna nomi",
                    ),
                ),
                (
                    "cleaning_start",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Tozalash boshlangan vaqt",
                    ),
                ),
                (
                    "cleaning_end",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Tozalash tugagan vaqt",
                    ),
                ),
                (
                    "sterilization_start",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Sterilizatsiya boshlangan vaqt",
                    ),
                ),
                (
                    "sterilization_end",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Sterilizatsiya tugagan vaqt",
                    ),
                ),
                (
                    "chemical_used",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ishlatilgan eritma va konsentratsiya",
                    ),
                ),
                (
                    "nurse_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Mas'ul hamshira",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sterilizatsiya jurnali",
                "verbose_name_plural": "Sterilizatsiya jurnallari",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="SurgeryTemplate",
        ),
    ]
