# Generated by Django 6.0.7 on 2026-07-16 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        db_index=True, verbose_name="Belgilangan vaqt"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=15, verbose_name="Davomiylik (daqiqa)"
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=255, verbose_name="Sabab"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Rejalashtirilgan"),
                            ("confirmed", "Tasdiqlangan"),
                            ("arrived", "Keldi"),
                            ("cancelled", "Bekor qilingan"),
                            ("no_show", "Kelmadi"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Izoh")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Shifokor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="patients.patient",
                        verbose_name="Bemor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yozilish",
                "verbose_name_plural": "Yozilishlar",
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(db_index=True, verbose_name="Tashrif sanasi"),
                ),
                (
                    "queue_number",
                    models.PositiveIntegerField(verbose_name="Navbat raqami"),
                ),
                ("complaint", models.TextField(blank=True, verbose_name="Shikoyat")),
                (
                    "referral",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Yo'llanma"
                    ),
                ),
                (
                    "preliminary_diagnosis",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Birlamchi tashxis"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Yaratildi"),
                            ("waiting", "Navbatda"),
                            ("accepted", "Qabul qilindi"),
                            ("in_progress", "Davolanmoqda"),
                            ("completed", "Yakunlandi"),
                            ("cancelled", "Bekor qilindi"),
                            ("archived", "Arxivlandi"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Bekor qilish sababi"
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Qabul vaqti"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yakun vaqti"
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit",
                        to="clinic_registration.appointment",
                        verbose_name="Yozilish",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Shifokor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="patients.patient",
                        verbose_name="Bemor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qabul (tashrif)",
                "verbose_name_plural": "Qabullar (tashriflar)",
                "ordering": ["-visit_date", "queue_number"],
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "scheduled_at"], name="clinic_regi_doctor__fb09a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["status", "visit_date"], name="clinic_regi_status_7690e6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.UniqueConstraint(
                fields=("visit_date", "queue_number"), name="uniq_queue_per_day"
            ),
        ),
    ]
