# Generated by Django 6.0.7 on 2026-07-16 09:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Karta raqami",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Familiya"),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ism")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Otasining ismi"
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Tug'ilgan sana")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Erkak"), ("female", "Ayol")],
                        max_length=10,
                        verbose_name="Jinsi",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon raqami +998901234567 formatida bo'lishi kerak.",
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "passport",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Pasport AA1234567 formatida bo'lishi kerak.",
                                regex="^[A-Z]{2}\\d{7}$",
                            )
                        ],
                        verbose_name="Pasport",
                    ),
                ),
                (
                    "jshshir",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="JSHSHIR 14 ta raqamdan iborat bo'lishi kerak.",
                                regex="^\\d{14}$",
                            )
                        ],
                        verbose_name="JSHSHIR",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="Manzil"),
                ),
                (
                    "relative_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Qarindoshi (FIO)"
                    ),
                ),
                (
                    "relative_phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon raqami +998901234567 formatida bo'lishi kerak.",
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Qarindoshi telefoni",
                    ),
                ),
                (
                    "insurance_company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Sug'urta kompaniyasi"
                    ),
                ),
                (
                    "insurance_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Sug'urta polisi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Izohlar")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bemor",
                "verbose_name_plural": "Bemorlar",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="patients_pa_last_na_1b32a7_idx",
                    ),
                    models.Index(fields=["phone"], name="patients_pa_phone_fc49bb_idx"),
                    models.Index(
                        fields=["birth_date"], name="patients_pa_birth_d_51eba5_idx"
                    ),
                ],
            },
        ),
    ]
