# Generated by Django 5.2.17 on 2026-08-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birth_certificate',
            field=models.CharField(blank=True, help_text='Bolalar uchun. Masalan: I-AB 123456', max_length=20, null=True, unique=True, verbose_name="Metrika (tug'ilganlik guvohnomasi)"),
        ),
    ]
