# Generated by Django 6.0.7 on 2026-07-16 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_display",
                    models.CharField(
                        blank=True,
                        help_text="User o'chirilsa ham kim ekani ko'rinib turadi.",
                        max_length=255,
                        verbose_name="Bajaruvchi (snapshot)",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Yaratildi"),
                            ("update", "O'zgartirildi"),
                            ("delete", "O'chirildi (soft)"),
                            ("restore", "Tiklandi"),
                            ("login", "Kirish"),
                            ("logout", "Chiqish"),
                            ("login_failed", "Kirish muvaffaqiyatsiz"),
                            ("approve", "Tasdiqlandi"),
                            ("export", "Eksport"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Amal",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, verbose_name="Model"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        verbose_name="Obyekt ID",
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=255, verbose_name="Obyekt"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"maydon": {"old": ..., "new": ...}} ko\'rinishida.',
                        verbose_name="O'zgarishlar",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP manzil"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Qurilma (User-Agent)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Vaqt"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bajaruvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit yozuvi",
                "verbose_name_plural": "Audit jurnali",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="audit_audit_model_n_20c0d3_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="audit_audit_actor_i_1175ab_idx",
                    ),
                ],
            },
        ),
    ]
