# Generated by Django 6.0.7 on 2026-07-16 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinic_registration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="O'lchov birligi"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Qisqartma"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "O'lchov birligi",
                "verbose_name_plural": "O'lchov birliklari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nomi")),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medicines",
                        to="pharmacy.measurementunit",
                        verbose_name="O'lchov birligi",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dori-darmon",
                "verbose_name_plural": "Dori-darmonlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MedicineBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True,
                        help_text="Avto-generatsiya qilinishi mumkin yoki zavod raqami",
                        max_length=100,
                        verbose_name="Partiya raqami",
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Kirim qilingan miqdor",
                    ),
                ),
                (
                    "quantity_available",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Qoldiq miqdor"
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Sotish narxi (shu partiya uchun)",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Kelish narxi",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Yaroqlilik muddati"
                    ),
                ),
                (
                    "received_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Kirim qilingan vaqt"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="pharmacy.medicine",
                        verbose_name="Dori-darmon",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kirim qiluvchi",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dori kirimi (Partiya)",
                "verbose_name_plural": "Dori kirimlari (Partiyalar)",
                "ordering": ["received_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicineDispense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Ishlatilgan miqdor",
                    ),
                ),
                (
                    "price_at_dispense",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tarix uchun partiya narxining nushasi",
                        max_digits=12,
                        verbose_name="Berilgan paytdagi narxi",
                    ),
                ),
                (
                    "dispensed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Berilgan vaqt"
                    ),
                ),
                (
                    "is_returned",
                    models.BooleanField(default=False, verbose_name="Qaytarilganmi?"),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Qaytarilgan vaqt"
                    ),
                ),
                (
                    "return_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Qaytarish sababi"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispenses",
                        to="pharmacy.medicinebatch",
                        verbose_name="Dori partiyasi (Kirim)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensed_medicines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Beruvchi xodim",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returned_dispenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qaytarib oldi",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensed_medicines",
                        to="clinic_registration.visit",
                        verbose_name="Bemor qabuli",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dori chiqimi (Bemorga)",
                "verbose_name_plural": "Dori chiqimlari",
                "ordering": ["-dispensed_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicinePriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Yaratilgan"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="O'chirilgan"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="O'chirilgan vaqt"
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Eski narx"
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Yangi narx"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="O'zgartirilgan vaqt"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="pharmacy.medicinebatch",
                        verbose_name="Dori partiyasi",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan xodim",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'chirgan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="O'zgartirgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Narx o'zgarish tarixi",
                "verbose_name_plural": "Narx o'zgarishlari",
                "ordering": ["-changed_at"],
            },
        ),
    ]
