# Generated by Django 5.2.16 on 2026-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedispense',
            name='is_package',
            field=models.BooleanField(default=False, verbose_name='Paket ichida (chekka tushmaydi)'),
        ),
    ]
