# Generated by Django 5.2.16 on 2026-07-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_medicinedispense_is_package"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicinedispense",
            options={
                "ordering": ["-dispensed_at"],
                "verbose_name": "Dori tayinlovi (Bemorga)",
                "verbose_name_plural": "Dori tayinlovlari",
            },
        ),
        migrations.AddField(
            model_name="medicinedispense",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Topshirilmadi"),
                    ("delivered", "Topshirildi"),
                    ("cancelled", "Bekor qilindi"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Holat",
            ),
        ),
    ]
