# Generated by Django 5.2.16 on 2026-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pharmacy",
            "0004_medicinerequest_medicinerequestitem_storagelocation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagelocation",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("main", "Asosiy Ombor"),
                    ("anesthesia", "Anesteziologiya Ombori"),
                    ("department", "Bo'lim Ombori"),
                ],
                default="main",
                max_length=20,
                verbose_name="Turi",
            ),
        ),
    ]
